### PR TITLE
Clean up features / hotfix for feaLib bug

### PR DESCRIPTION
**Pull request by jamesgk**
Ignore the name of the branch, that was originally going to be my approach but then I decided rearranging things in the features was easier.

The main point of this PR is the last commit. It only looks huge because of the first commit, which unfortunately affected almost every line in the feature file because they had weird line endings.

### CODE REVIEW

**Comment by jamesgk** [comment]
BTW, this is what I used to detect problematic classes. It's kinda quick and dirty: https://gist.github.com/jamesgk/89be1b765e491d41d3e1

**Comment by dougfelt** [comment]
LGTM.  I can't comment on the actual substance of these changes, of course...

**Comment by jamesgk** [comment]
Hmm. A sanity check from someone who knows Roboto feature expectations / adobe feature syntax could be helpful. @roozbehp / @brawer?

**Comment by jamesgk** [comment]
Though, it's kind of a pain that the diffs are only line-by-line and don't show what was added / removed from a line. Makes seeing what was added / removed from classes overly tedious.

**Comment by dougfelt** [comment]
Yeah, that's what I found.  I eyeballed a few places where something had
been moved/changed but of course that's very incomplete.

**Pull request merged**
