### PR TITLE
subset webfonts when running make

### PR DESCRIPTION
**Pull request by m4rc1e**
When running `make web`, the Fontmake file didn't apply `subset_for_web.py`. The webfonts hosted at https://fonts.google.com/specimen/Roboto have been subsetted.

Unless anyone can point me to a set of webfonts which have the full character set, I think make should apply this.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Ok, once the files have been subsetted, running run_web_tests.py fails on 3 tests

```
FAIL: test_c2sc_coverage (__main__.TestFeatures)
Tests that c2sc is supported for a required set.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marc/Documents/googlefonts/manual_font_cleaning/roboto/env/lib/python2.7/site-packages/nototools/unittests/font_tests.py", line 461, in test_c2sc_coverage
    self.run_sub_coverage_test('c2sc', self.c2sc_reqs_path)
  File "/Users/marc/Documents/googlefonts/manual_font_cleaning/roboto/env/lib/python2.7/site-packages/nototools/unittests/font_tests.py", line 451, in run_sub_coverage_test
    (feature, u''.join(chars_with_no_sub).encode('UTF-8'))))
AssertionError: c2sc feature is not applied correctly to '&ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞĀĂĄĆĈĊČĎĐĒĔĖĘĚĜĞĠĢĤĦĨĪĬĮĲĴĶĹĻĽĿŁŃŅŇŊŌŎŐŒŔŖŘŚŜŞŠŢŤŦŨŪŬŮŰŲŴŶŸŹŻŽǺǼǾȘΆΈΉΊΌΎΏΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΪΫЁЂЃЄЅІЇЈЉЊЋЌЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯҐẀẂẄẞỲ'

======================================================================
FAIL: test_smcp_coverage (__main__.TestFeatures)
Tests that smcp is supported for a required set.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marc/Documents/googlefonts/manual_font_cleaning/roboto/env/lib/python2.7/site-packages/nototools/unittests/font_tests.py", line 456, in test_smcp_coverage
    self.run_sub_coverage_test('smcp', self.smcp_reqs_path)
  File "/Users/marc/Documents/googlefonts/manual_font_cleaning/roboto/env/lib/python2.7/site-packages/nototools/unittests/font_tests.py", line 451, in run_sub_coverage_test
    (feature, u''.join(chars_with_no_sub).encode('UTF-8'))))
AssertionError: smcp feature is not applied correctly to '&abcdefghijklmnopqrstuvwxyzßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿāăąćĉċčďđēĕėęěĝğġģĥħĩīĭįıĳĵķĺļľŀłńņňŋōŏőœŕŗřśŝşšţťŧũūŭůűųŵŷźżžǻǽǿșάέήίαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώабвгдежзийклмнопрстуфхцчшщъыьэюяёђѓєѕіїјљњћќўџґẁẃẅỳ'

======================================================================
FAIL: test_unic_coverage (__main__.TestFeatures)
Tests that unic is supported for a required set.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marc/Documents/googlefonts/manual_font_cleaning/roboto/env/lib/python2.7/site-packages/nototools/unittests/font_tests.py", line 466, in test_unic_coverage
    self.run_sub_coverage_test('unic', self.unic_reqs_path)
  File "/Users/marc/Documents/googlefonts/manual_font_cleaning/roboto/env/lib/python2.7/site-packages/nototools/unittests/font_tests.py", line 451, in run_sub_coverage_test
    (feature, u''.join(chars_with_no_sub).encode('UTF-8'))))
AssertionError: unic feature is not applied correctly to 'AEMNUabcdefghijklmnopqrstuvwxyzÀÁÂÃÄÅÈÉÊËÑÙÚÜàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿĀāĂăĄąćĉċčďđĒēĔĕĖėĘęĚěĝğġģĥħĩīĭįĳĵķĺļľŀŃńŅņŇňŋōŏőœŕŗřśŝşšţťŧŨũŪūŬŭŮůŰűŲųŵŷźżžǺǻǽǿșẁẃẅỳ'
```

Keep this open while I investigate.

Previous subsetted webfonts also fail on these tests.

**Comment by davelab6** [comment]
> Unless anyone can point me to a set of webfonts which have the full character set, I think make should apply this.

I agree; the Google Fonts API doesn't want to increase filesize and thus latency.

**Comment by m4rc1e** [comment]
Webfont tests have been updated.

**Comment by davelab6** [comment]
Great! Per @roozbehp request, I have assigned @dougfelt as a reviewer, who I hope can use the Github review system to confirm this is good to merge :)

**Comment by dougfelt** [comment]
LGTM

**Comment by davelab6** [comment]
Thank you Doug!!

**Pull request merged**
