### PR TITLE
TTF generation

### PR DESCRIPTION
**Pull request by jamesgk**
Kind of a lot of stuff here. But basically this just uses ufo2fdk to create a TTF outline, then copies in GPOS and GSUB tables from makeotf output. The cubic-to-quadratic curve conversion code is also cleaned up a bit.

### CODE REVIEW

**Comment by Richard1500** [comment]
sometimes I can come here.

**Comment by Richard1500** [comment]
OKay,sometimes, I can watch blue movies, which makes me sick, but sometimes, which is attractive foe me.Please tell me reason.Thank you.

**Comment by anthrotype** [comment]
This is very good! It would be nice if @jamesgk contributed his outline TTF compiler to ufo2fdk... ;-)

**Comment by jamesgk** [comment]
@anthrotype I'd be happy to! I do think it makes more sense to have it there. Though I already have a related pull request to ufo2fdk which has been open for a while.

**Comment by anthrotype** [comment]
I'm sure Tal has simply forgotten about it. He'll be happy to welcome this contribution.

**Comment by anthrotype** [comment]
@jamesgk if I may add one more wish, it'd be nice to have a TTGlyphPen like yours available in fontTools' default set of pens...

**Comment by adrientetar** [comment]
This would be great indeed. :cherries:

**Comment by behdad** [comment]
Note that James's implementation is not an accurate conversion, so I don't want to promote it further.  James and I will work on a robust and accurate implementation, and at that point I'll move it to fonttools.  Same about the CFF pen from ufo2fdk.

**Comment by adrientetar** [comment]
[QuadraticConverter](https://github.com/sansplomb/QuadraticConverter/blob/master/QuadraticConverter.roboFontExt/lib/QuadraticConverter.py) seems a more extensive converter. It does not have a permissive license though.

**Comment by davelab6** [comment]
Did you reach an agreement offline?

**Comment by adrientetar** [comment]
Well, I have not heard back from them. I'm mostly on things that relate to early parts of the design process these days so I haven't reached out more since then.

**Comment by davelab6** [comment]
cc @JeremieTypefactory

**Comment by sansplomb** [comment]
QuadraticConverter is now liberated, it has a BSD3 license.
https://github.com/sansplomb/QuadraticConverter

**Comment by anthrotype** [comment]
:100:

**Comment by davelab6** [comment]
Thanks Jeremie!

**Comment by adrientetar** [comment]
Cool! I plan to make a cross-platform variant of this that would also be usable from command-line.

**Comment by jamesgk** [comment]
So, there's been a couple of updates here, we are:

1. approximating the cubics in such a way that the tangents at the curve ends are preserved
2. optionally converting respective curves from multiple fonts at once to ensure interpolation compatibility.

Check out 05bbe66 and 1a69a2d for implementation details. With b1a2af2 we also try an intersection approximation method first just to see if we can get away with fewer control points.

@behdad, if this looks good to you I will merge into master. Then there's the question of moving modules around i.e. OutlineTTFCompiler to ufo2fdk and TTGlyphPen to FontTools.

**Comment by behdad** [comment]
Thanks @jamesgk, that's great.  I'll review the code but won't have cycles to review its performance in action.  Would be great if @anthrotype can give it a spin and report.

cc @twardoch

**Comment by anthrotype** [comment]
Sure, I'll have a look as well, as soon as I can.
Thanks a lot for contributing this!

**Comment by behdad** [comment]
> Sure, I'll have a look as well, as soon as I can.
> Thanks a lot for contributing this!

Thanks Cosimo!  In particular, comparison to QuadraticConverter as well as your secret sauce is appreciated :D.

**Comment by behdad** [comment]
James: would be nice to replace numpy usage with something else.  numpy is not available in jython or pypy, so we try to avoid it.

**Comment by jamesgk** [comment]
Done. It would have been nice to use the RPoints themselves for point arithmetic but I found that it slowed the whole conversion process by about 10 times.

**Comment by adrientetar** [comment]
Robofab is slow. Defcon is more barebone (less convenience APIs, data isn't hidden behind a façade) but much faster.

**Comment by behdad** [comment]
> It would have been nice to use the RPoints themselves for point arithmetic but I found that it slowed the whole conversion process by about 10 times.

Yeah, that's a Python problem.  I faced the same issue when porting GLyphy algorithms to Python (https://github.com/rougier/gl-bezier/blob/master/behdad.py )

**Comment by adrientetar** [comment]
You can use slots otherwise in order to avoid dict-class overhead.

**Comment by behdad** [comment]
> You can use slots otherwise in order to avoid dict-class overhead.

slots help with memory usage but not much with speed.  It's the churn of creating and disposing small objects all the time that kills doing point math using Python objects.

**Comment by behdad** [comment]
The docstring at the top needs to be updated as well.

**Comment by jamesgk** [comment]
> slots help with memory usage but not much with speed. It's the churn of creating and disposing small objects all the time that kills doing point math using Python objects.

Well, somehow using this inline Point class seems to be okay. I think there's overhead with RoboFab objects (having custom methods that remember additional state for almost every attribute read / write) which makes them particularly slow.

Still, the curve conversion is quite slow. Are there options for speed-up besides implementing this in C and wrapping it in a module (presumably that would introduce the same concerns as numpy)?

> You might as well make these all be methods on Point().

Any opinion on using Defcon instead of this Point class? It does seem to be duplicated functionality, though the class is small and there's the cost of introducing additional dependencies.

Personally I wouldn't want to use Defcon at all unless we completely replace RoboFab with it, which is a bigger task. Am I right in thinking that Defcon is a better fit for this toolchain, since we don't use RoboFont or FontLab?

**Comment by behdad** [comment]
> Still, the curve conversion is quite slow. Are there options for speed-up besides implementing this in C and wrapping it in a module (presumably that would introduce the same concerns as numpy)?

My gut feeling is that you'd get a good boost by spelling out bezierAt for cubic and quadratic.  I was slightly surprised that you didn't create Bezier classes.  What you've got is rather smart, but not the fastest I think.

>     You might as well make these all be methods on Point().
> 
> Any opinion on using Defcon instead of this Point class? It does seem to be duplicated functionality, though the class is small and there's the cost of introducing additional dependencies.

The class is definitely small enough to keep in house.  

> Personally I wouldn't want to use Defcon at all unless we completely replace RoboFab with it, which is a bigger task. Am I right in thinking that Defcon is a better fit for this toolchain, since we don't use RoboFont or FontLab?

I never fully understood the relationship of defcon and RoboFab.  From my limited understanding, what you suggest makes sense, yes.

**Comment by adrientetar** [comment]
> Am I right in thinking that Defcon is a better fit for this toolchain, since we don't use RoboFont or FontLab?

Robofont itself uses defcon (it was made to build applications on top of it), you can get a defcon object in robofont with font.naked()

**Comment by jamesgk** [comment]
I'm going to close and re-open this pull request, since much of the code here has since been moved out of this repository.

**Pull request closed without merging**
