### PR TITLE
Fontcrunch update

### PR DESCRIPTION
**Pull request by jamesgk**
This fixes a variety of bugs which have been filed against fontcrunch:
https://github.com/googlefonts/fontcrunch

### CODE REVIEW

**Comment by anthrotype** [comment]
just wondering: why aren't you using git submodule instead of having a full copy of fontcrunch inside roboto's repo? Is the copy in third_party folder any different from the upstream https://github.com/googlefonts/fontcrunch?

**Comment by dougfelt** [comment]
lgtm

**Comment by behdad** [comment]
> just wondering: why aren't you using git submodule instead of having a full copy of fontcrunch inside roboto's repo? Is the copy in third_party folder any different from the upstream https://github.com/googlefonts/fontcrunch?

We should.  When this codebase started at Google, fontcrunch wasn't publicly available yet...

**Comment by anthrotype** [comment]
I see, ok!

**Pull request merged**
