### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by huslage**
Added `Dockerfile` to obviate the need for people to install dependencies locally.

### CODE REVIEW

**Comment by jamesgk** [comment]
The direction we want to go in re: easing installation is to use git submodules, do you think that could be a viable alternative to Docker?

**Comment by huslage** [comment]
I think submodules are really brittle and hard to use. But there's no reason you couldn't do both. I"m happy to maintain this Dockerfile.

In fact, this Dockerfile probably needs to specify git commit IDs so that it's reproducible.

**Comment by davelab6** [comment]
@huslage would you be interested in bringing this up to date? :)

**Comment by huslage** [comment]
Sure

**Comment by jamesgk** [comment]
We ended up using pip to make setup easier, so I don't think we're going to merge this.

**Pull request closed without merging**
