### PR TITLE
Fixed typographical error, changed availabe to available in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
google, I've corrected a typographical error in the documentation of the [roboto](https://github.com/google/roboto) project. You should be able to merge this pull request automatically. However, if this was intentional or you enjoy living in linguistic squalor please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by jamesgk** [comment]
We certainly don't want to live in linguistic squalor! However I'm not sure what's our protocol on handling contributions from a bot so I'll close this and fix the typo myself.

**Comment by thoppe** [comment]
Out of curiosity (since there is a real person behind this two-day-old bot), why couldn't you accept a change from a bot? Is it a licensing problem?

**Comment by jamesgk** [comment]
Yep

**Comment by thoppe** [comment]
So if a licence* was added (especially in the message) would this be
sufficient? I ask because I've submitted a pull request to an MS repo and
got a similar response.

*Something to the effect of all edits are freely given to the public domain?

**Comment by jamesgk** [comment]
I doubt it. With cases like this I'd probably refer to a legal department for guidance. It's a little insane but such is the nature of working with large companies I suppose. Which is why it's easier to just reject the PR.

(I do know off the top of my head that public domain != licensed)

**Comment by thoppe** [comment]
Understood! Thanks for the information.

I'm going to be using the number of successful pull requests as a marker
for the efficacy of the bot, so I have slightly selfish reasons for
increasing the number of pulls. :)

Also, thanks for you (and google) working on open-source projects!

**Comment by dougfelt** [comment]
See the CONTRIBUTING.md file.  Basically you need to sign an agreement
before we can accept patches.  Small spelling corrections like this,
though, we should be able to take regardless.

**Pull request closed without merging**
